version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=WazePeruvian
    restart: always

  frontend:
    build:
      context: ../front-TI/front-ti
      dockerfile: Dockerfile    
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data: